set background=dark
syntax on
set guifont=Ubuntu\ Mono\ 12
colorscheme molokai

"Set up based on an environment variable"
let iru=$IRU

set backupdir=~/tmp/vim//
set directory=~/tmp/vim//

nmap <silent> <c-n> :NERDTreeToggle<CR>

" puppet stuff "
au BufRead,BufNewFile *.pp   setfiletype puppet
:autocmd FileType puppet set shiftwidth=2
:autocmd FileType puppet set softtabstop=2
:autocmd FileType puppet set autoindent
:autocmd FileType puppet set smartindent

" ruby syntax "
au BufRead,BufNewFile *.rb   setfiletype ruby
:autocmd FileType ruby set shiftwidth=2
:autocmd FileType ruby set softtabstop=2
:autocmd FileType ruby set autoindent
:autocmd FileType ruby set smartindent

function! UseTruliaStyle()
	colorscheme industry
endfunction

if iru == "trulia"
	call UseTruliaStyle()
endif


" If the Hack Regular font exists - go ahead and use that "

let font = {"name" : "Hack Regular", "size" : "12"}

call system("fc-list -q " . font.name)
if has("unix") && !v:shell_error
    let &guifont=join(values(font))
end
