" pathogen goes first because lots of other stuff follows "
call pathogen#infect() 

:syntax enable
:set background=dark
:set ruler
:set nomodeline
:set t_Co=256

if $TERM == 'screen'
  set term=xterm
endif


nmap <silent> <c-n> :NERDTreeToggle<CR> 

" Turn on spell check for mail "
:autocmd FileType mail setlocal spell spelllang=en_us

" Title string stuff "
let &titlestring = hostname() . "[vim(" . expand("%:t") . ")]"

if &term == "screen"
  set t_ts=^[k
  set t_fs=^[\
endif

if &term == "screen" || &term == "xterm"
  set title
endif


" puppet manifests "
au BufRead,BufNewFile *.pp   setfiletype puppet
:autocmd FileType puppet set shiftwidth=2
:autocmd FileType puppet set softtabstop=2
:autocmd FileType puppet set autoindent
:autocmd FileType puppet set smartindent
:autocmd FileType puppet map <F9> :w<CR>:!puppet-lint --no-80chars-check %<CR>

" ruby syntax "
au BufRead,BufNewFile *.rb   setfiletype ruby
:autocmd FileType ruby set shiftwidth=2
:autocmd FileType ruby set softtabstop=2
:autocmd FileType ruby set autoindent
:autocmd FileType ruby set smartindent
:autocmd FileType ruby map <F9> :w<CR>:!ruby -c %<CR>

" python syntax "
au BufRead,BufNewFile *.py   setfiletype python
:autocmd FileType python set shiftwidth=4
:autocmd FileType python set softtabstop=4
:autocmd FileType python set autoindent
:autocmd FileType python set smartindent

" cucumber files "
au Bufread,BufNewFile *.feature setfiletype cucumber
:autocmd FileType cucumber set shiftwidth=2
:autocmd FileType cucumber set softtabstop=2
:autocmd FileType cucumber set autoindent
:autocmd FileType cucumber set smartindent

" nagios/icinga files "
au Bufread,BufNewFile *.cfg setfiletype icinga
:autocmd FileType icinga set shiftwidth=2
:autocmd FileType icinga set softtabstop=2
:autocmd FileType icinga set autoindent
:autocmd FileType icinga set smartindent

" tritium scripts "
au BufRead,BufNewFile *.ts,*.rs set filetype=tritiumscript
:autocmd FileType tritumscript set shiftwidth=2
:autocmd FileType tritumscript set softtabstop=2
:autocmd FileType tritumscript set autoindent
:autocmd FileType tritumscript set smartindent
