" Vundle and bundles configuration
source ~/.dotfiles/vim/bundles.vim

:syntax enable
:set background=dark
:set ruler
:set nomodeline
:set t_Co=256
:set showcmd

if $TERM == 'screen'
  set term=xterm
endif

set backupdir=~/tmp/vim//
set directory=~/tmp/vim//

" On OSX
vmap <D-c> y:call system("pbcopy", getreg("\""))<CR>
nmap <D-v> :call setreg("\"",system("pbpaste"))<CR>p

nmap <silent> <c-n> :NERDTreeToggle<CR> 
nmap <silent> <c-o> :FufFile **/<CR>
nmap <silent> <c-y> :tabnew<CR>

" Turn on spell check for mail "
:autocmd FileType mail setlocal spell spelllang=en_us

" Title string stuff "
let &titlestring = hostname() . "[vim(" . expand("%:t") . ")]"

if &term == "screen"
  set t_ts=^[k
  set t_fs=^[\
endif

if &term == "screen" || &term == "xterm"
  set title
endif


" puppet manifests "
au BufRead,BufNewFile *.pp   setfiletype puppet
:autocmd FileType puppet set shiftwidth=2
:autocmd FileType puppet set softtabstop=2
:autocmd FileType puppet set autoindent
:autocmd FileType puppet set smartindent
:autocmd FileType puppet set expandtab
:autocmd FileType puppet map <c-l> :call VimuxRunCommand("clear; rake")<CR>
:autocmd FileType puppet map <c-k> :w<CR>:Tabularize /=><CR>

" ruby syntax "
au BufRead,BufNewFile *.rb   setfiletype ruby
:autocmd FileType ruby set shiftwidth=2
:autocmd FileType ruby set softtabstop=2
:autocmd FileType ruby set autoindent
:autocmd FileType ruby set smartindent
:autocmd FileType ruby set expandtab
:autocmd FileType ruby map <F9> :w<CR>:!ruby -c %<CR>

" golang syntax "
au BufRead,BufNewFile *.go set filetype=go
:autocmd FileType go map <F9> :w<CR>:!go build %<CR>

" python syntax "
au BufRead,BufNewFile *.py   setfiletype python
:autocmd FileType python set shiftwidth=4
:autocmd FileType python set softtabstop=4
:autocmd FileType python set autoindent
:autocmd FileType python set smartindent

" cucumber files "
au Bufread,BufNewFile *.feature setfiletype cucumber
:autocmd FileType cucumber set shiftwidth=2
:autocmd FileType cucumber set softtabstop=2
:autocmd FileType cucumber set autoindent
:autocmd FileType cucumber set smartindent

" nagios/icinga files "
au Bufread,BufNewFile *.cfg setfiletype icinga
:autocmd FileType icinga set shiftwidth=2
:autocmd FileType icinga set softtabstop=2
:autocmd FileType icinga set autoindent
:autocmd FileType icinga set smartindent

" erlang files "
au BufRead,BufNewFile *.erl set filetype=erlang

" puppet manifests "
au BufRead,BufNewFile *.md   setfiletype markdown

" vimwiki stuff "
" Run multiple wikis "
let g:vimwiki_list = [
			\{'path': '~/Documents/VimWiki/tech.wiki'},
			\{'path': '~/Documents/VimWiki/customer.wiki/cpf.wiki'},
			\{'path': '~/Documents/VimWiki/customer.wiki/whistle.wiki'} 
		\]
au BufRead,BufNewFile *.wiki set filetype=vimwiki
:autocmd FileType vimwiki map <F9> :VimwikiMakeDiaryNote<CR>
function! ToggleCalendar()
  execute ":Calendar"
  if exists("g:calendar_open")
    if g:calendar_open == 1
      execute "q"
      unlet g:calendar_open
    else
      g:calendar_open = 1
    end
  else
    let g:calendar_open = 1
  end
endfunction
:autocmd FileType vimwiki map <F8> :call ToggleCalendar()<CR>
